/* eslint-disable max-len */
/* eslint-disable no-unused-vars */
import {longest} from './leetcode/longestpalindrome/longestpalindrome.spec.js';
import {longestSubstring} from './leetcode/longestsubstring/longestsubstring.spec.js';
import {numberIsPalindrome_} from './leetcode/palindromenumber/palindrome-number.spec.js';
import {romanToInt_} from './leetcode/roman-integer-13/roman-number.spec.js';
import {longestCommonPrefix_} from './leetcode/longest-common-prefix-14/longest-common-prefix.spec.js';
import {isValid_} from './leetcode/valid-parentheses-20/valid-parentheses.spec.js';
import {mergeTwoLists_} from './leetcode/merge-two-lists-21/merge-two-lists.spec.js';
import {removeDuplicates_} from './leetcode/remove-duplicates-from-sorted-array-26/remove-duplicates-sorted-array.spec.js';
import {searchInsert_} from './leetcode/search-insert-position-35/search-insert-position.spec.js';
import {removeElement_} from './leetcode/remove-element-27/remove-element.spec.js';
import {strStr_} from './leetcode/find-1st-index-of-1st-occurence-28/find-1st-index-of-1st-occurence.spec.js';
import {lengthOfLastWord_} from './leetcode/length-last-word-58/length-last-word.spec.js';
import {plusOne_} from './leetcode/plus-one-66/plus-one.spec.js';
import {merge_} from './leetcode/merge-sorted-array-88/merge-sorted-array.spec.js';
import {isPalindrome_} from './leetcode/valid-palindrome-125/valid-palindrome.spec.js';
import {mergeAlternately_} from './leetcode/merge-strings-alternately-1768/merge-strings-alternately.spec.js';
import {findSpecialInteger_} from './leetcode/element-appearing-25plus-in-array-1287/element-appearing-25plus-in-array.spec.js';
import './leetcode/group-anagrams-49/group-anagrams.spec.js';
import './leetcode/maximum-product-two-elements-in-array-1464/maximum-product.spec.js';
import './leetcode/top-K-frequent-elements-347/top-K-frequent-elements.spec.js';
import './leetcode/product-of-array-except-self-238/product-of-array.spec.js';
import './leetcode/difference-between-ones-zeros-2482/diff-between-ones-zeros.spec.js';
import './leetcode/longest-consecutive-sequence-128/longest-consecutive-sequence.spec.js';
import './leetcode/consecutive-characters-1446/consecutive-characters.spec.js';
import './leetcode/single-number-136/single-number.spec.js';
import './leetcode/maximum-product-difference-2-pairs-1913/maximum-product-2-pairs.spec.js';
import './leetcode/image-smoother-661/image-smoother.spec.js';
import './leetcode/wildest-vertical-area-1637/wildest-vertical-area-1637.spec.js';
import './leetcode/maximum-score-1422/maximum-score.spec.js';
import './leetcode/path-crossing-1496/path-crossing.spec.js';
import './leetcode/search-in-rotated-sorted-array-33/search-rotated-sorted-array.spec.js';
import './leetcode/evaluate-reverse-polish-notation-150/evaluate-reverse-polish-notation.spec.js';
